name: mmdet_ws1
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - blas=1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - cffi=2.0.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-opencl=13.1.80
  - cuda-runtime=11.8.0
  - cuda-version=13.1
  - dav1d=1.2.1
  - expat=2.7.3
  - ffmpeg=4.2.2
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2021.4.0
  - jpeg=9f
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.16.0.49
  - libcurand=10.4.1.34
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjitlink=12.1.105
  - libnvjpeg=11.9.0.86
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpng=1.6.50
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.7.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.7.3
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openh264=2.1.1
  - openssl=3.0.18
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - torchaudio=2.1.2
  - torchtriton=3.1.0
  - torchvision=0.16.2
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - x264=1!157.20191217
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.2
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - jmespath==0.10.0
      - kiwisolver==1.4.9
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - networkx==3.3
      - numpy==2.2.6
      - opencv-python==4.9.0.80
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pillow==11.0.0
      - platformdirs==4.5.0
      - pycocotools==2.0.10
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - requests==2.28.2
      - rich==13.4.2
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==2.1.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - tomli==2.3.0
      - tqdm==4.65.2
      - tzdata==2025.2
      - urllib3==1.26.20
      - yapf==0.43.0
prefix: /home/hansung/anaconda3/envs/mmdet_ws1
