name: mmdet-fresh
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.2
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - idna==3.11
      - jinja2==3.1.4
      - jmespath==0.10.0
      - kiwisolver==1.4.9
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pillow==11.0.0
      - platformdirs==4.5.0
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - requests==2.28.2
      - rich==13.4.2
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==2.1.2
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - tomli==2.3.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.65.2
      - triton==3.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - yapf==0.43.0
prefix: /home/hansung/anaconda/envs/mmdet-fresh
